const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reducedMotion){document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));}
const menu=document.querySelector('.menu-toggle');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu');document.querySelector('#nav').classList.toggle('open',open)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu?.getAttribute('aria-expanded')==='true'){menu.click();menu.focus()}});
const video=document.querySelector('video');let motionPaused=reducedMotion;
if(reducedMotion)video?.pause();
document.querySelector('#motion-toggle')?.addEventListener('click',e=>{motionPaused=!motionPaused;document.body.classList.toggle('motion-paused',motionPaused);if(motionPaused)video.pause();else video.play().catch(()=>{});e.currentTarget.textContent=motionPaused?'▶':'Ⅱ';e.currentTarget.setAttribute('aria-label',motionPaused?'Play background motion':'Pause background motion')});
let scheduled=false;window.addEventListener('scroll',()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{const total=document.documentElement.scrollHeight-innerHeight;document.querySelector('.reading-progress').style.width=(total?scrollY/total*100:0)+'%';scheduled=false})},{passive:true});
const url=new URL(location.href);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const capInput=document.querySelector('#cap-query');
if(capInput){let rows=[],page=0,category=url.searchParams.get('category')||'all';if(!['all','engine','hydraulics','apu','airframe','actuators'].includes(category))category='all';capInput.value=url.searchParams.get('q')||'';const pageSize=20;
const matchesCategory=r=>{const d=r[2].toLowerCase(),app=r[5].toLowerCase();if(category==='all')return true;if(category==='hydraulics')return /^29/.test(r[4])||/hydraulic/.test(d);if(category==='apu')return /apu|gtcp|131-9|331-|85-/.test(d+' '+app);if(category==='engine')return /cfm|cf6|pw|rb211|v2500|engine/.test(d+' '+app);if(category==='airframe')return /^2[1789]|^3[26]/.test(r[4])&&!/apu/.test(d+' '+app);return /actuator|control/.test(d)};
function render(){const q=capInput.value.trim().toLowerCase();const tokens=q.split(/\s+/).filter(Boolean);const filtered=rows.filter(r=>matchesCategory(r)&&tokens.every(t=>r.slice(1).some(v=>String(v).toLowerCase().includes(t))));const pages=Math.ceil(filtered.length/pageSize);page=Math.min(page,Math.max(0,pages-1));document.querySelector('#cap-results').innerHTML=filtered.slice(page*pageSize,(page+1)*pageSize).map(r=>'<tr><td><a href="component.html?part='+encodeURIComponent(r[1])+'">'+esc(r[1])+'</a></td><td>'+esc(r[2])+'</td><td>'+esc(r[3])+'</td><td>'+esc(r[4])+'</td><td>'+esc(r[5])+'</td><td><a class="table-action" href="quote.html?part='+encodeURIComponent(r[1])+'&application='+encodeURIComponent(r[5])+'">Get a quote ↗</a></td></tr>').join('');document.querySelector('#results-status').textContent=filtered.length.toLocaleString()+' matching records'+(q?' for “'+capInput.value.trim()+'”':'')+' · Published capability list';document.querySelector('#page-status').textContent=pages?'Page '+(page+1)+' of '+pages:'';document.querySelector('#prev-page').disabled=page===0;document.querySelector('#next-page').disabled=page>=pages-1;document.querySelector('#empty-results').hidden=filtered.length>0;document.querySelector('#results-table').hidden=!filtered.length;document.querySelector('.pagination').hidden=!filtered.length;document.querySelector('#empty-quote').href='quote.html?part='+encodeURIComponent(capInput.value.trim());document.querySelectorAll('[data-category]').forEach(b=>{const active=b.dataset.category===category;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});url.searchParams.set('q',capInput.value);url.searchParams.set('category',category);history.replaceState({},'',url);}
fetch('assets/capabilities.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{rows=d.rows;render()}).catch(()=>{document.querySelector('#results-status').textContent='The capability list could not be loaded. Please reload or send us your part number.';document.querySelector('#empty-results').hidden=false;document.querySelector('#results-table').hidden=true;document.querySelector('.pagination').hidden=true});
capInput.addEventListener('input',()=>{page=0;render()});document.querySelector('#capability-search').addEventListener('submit',e=>{e.preventDefault();page=0;render()});document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;page=0;render()}));document.querySelector('#prev-page').addEventListener('click',()=>{page--;render();document.querySelector('#results-status').scrollIntoView({block:'start'})});document.querySelector('#next-page').addEventListener('click',()=>{page++;render();document.querySelector('#results-status').scrollIntoView({block:'start'})});}
const quote=document.querySelector('#quote-form');if(quote){quote.elements.part.value=url.searchParams.get('part')||'';quote.elements.application.value=url.searchParams.get('application')||'';quote.elements.quantity.value='1';quote.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(quote);const labels={part:'Part number',alternate:'Alternate / OEM',quantity:'Quantity',application:'Application',condition:'Condition',needed:'Needed by',company:'Company',name:'Name',email:'Email',phone:'Phone',notes:'Notes'};document.querySelector('#quote-summary-text').textContent=[...data].filter(([k,v])=>v).map(([k,v])=>labels[k]+': '+v).join('\n');quote.hidden=true;const panel=document.querySelector('#quote-summary');panel.hidden=false;panel.setAttribute('tabindex','-1');panel.focus();panel.scrollIntoView({block:'center'})});document.querySelector('#edit-quote').addEventListener('click',()=>{document.querySelector('#quote-summary').hidden=true;quote.hidden=false;quote.elements.part.focus()})}
if(document.querySelector('#component-record')){const part=url.searchParams.get('part');if(part)fetch('assets/capabilities.json').then(r=>r.json()).then(d=>{const r=d.rows.find(r=>r[1]===part);if(!r){document.querySelector('#component-record').textContent='This part number is not listed. Please request a quote for confirmation.';return}document.querySelector('.page-hero h1').textContent=r[2];document.querySelector('.page-hero>p').textContent='Part number '+r[1]+' · '+r[3]+' · '+r[5];document.title=r[1]+' — '+r[2]+' | HSA';document.querySelector('.breadcrumbs').innerHTML='<a href="index.html">Home</a> / <a href="capabilities.html">Capabilities</a> / '+esc(r[1]);document.querySelector('.page-hero .eyebrow').textContent='COMPONENT / '+r[1];document.querySelector('#component-record').innerHTML='<div class="demo-note">Published capability record: <strong>'+esc(r[1])+'</strong><br>Manufacturer: '+esc(r[3])+'<br>ATA: '+esc(r[4])+'<br>Application: '+esc(r[5])+'</div>';document.querySelector('#article-quote').href='quote.html?part='+encodeURIComponent(r[1])+'&application='+encodeURIComponent(r[5]);document.querySelectorAll('.article-copy>h2,.article-copy>p').forEach(el=>el.remove());document.querySelector('#component-record').insertAdjacentHTML('afterend','<h2>Repair and overhaul support</h2><p>Send us the part number, current condition and required return date. HSA will confirm the applicable workscope and quote for your component.</p>')}).catch(()=>{document.querySelector('#component-record').textContent='This record could not be loaded. Please request a quote.'})}
if(!reducedMotion){const numbers=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const node=entry.target,target=Number(node.dataset.count),start=performance.now();node.setAttribute('aria-label',target.toLocaleString());const tick=now=>{const p=Math.min((now-start)/1050,1);node.textContent=Math.round(target*(1-Math.pow(1-p,3))).toLocaleString();if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);numbers.unobserve(node)}),{threshold:.8});document.querySelectorAll('[data-count]').forEach(node=>numbers.observe(node))}
// Match the existing site's instant, component-grouped homepage search.
const heroInput=document.querySelector('#hero-search');
if(heroInput){
 const results=document.querySelector('#hero-results'),status=document.querySelector('#hero-search-status');
 const normalize=value=>String(value??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
 let dataPromise;
 const load=()=>dataPromise||(dataPromise=fetch('assets/capabilities.json').then(r=>{if(!r.ok)throw Error('Catalog unavailable');return r.json()}).then(d=>d.rows).catch(e=>{dataPromise=null;throw e}));
 function close(){results.hidden=true;results.replaceChildren();heroInput.setAttribute('aria-expanded','false')}
 function show(){results.hidden=false;heroInput.setAttribute('aria-expanded','true')}
 function score(row,q){const pn=normalize(row[1]),desc=normalize(row[2]);return pn===q?0:pn.startsWith(q)?1:desc===q?2:desc.startsWith(q)?3:pn.includes(q)?4:desc.includes(q)?5:6}
 function summarize(rows,index,limit){const values=[...new Set(rows.map(r=>r[index]).filter(Boolean))];return values.slice(0,limit).join(', ')+(values.length>limit?' +'+(values.length-limit)+' more':'')}
 async function search(){
  const q=normalize(heroInput.value);
  if(q.length<2){close();status.textContent=q?'Enter at least two characters to search.':'';return}
  status.textContent='Searching capabilities…';
  try{
   const rows=await load();if(normalize(heroInput.value)!==q)return;
   const grouped=new Map();
   rows.forEach(row=>{if(!normalize(row.slice(1).join(' ')).includes(q))return;const key=normalize(row[2]);if(!grouped.has(key))grouped.set(key,{description:row[2],rows:[],score:6});const group=grouped.get(key);group.rows.push(row);group.score=Math.min(group.score,score(row,q))});
   const groups=[...grouped.values()].sort((a,b)=>a.score-b.score||a.description.localeCompare(b.description));
   results.innerHTML=groups.slice(0,8).map(g=>'<a class="hero-result" href="capabilities.html?q='+encodeURIComponent(g.description)+'" aria-label="View all '+esc(g.description)+' capabilities"><strong>'+esc(g.description)+'</strong><p>Part numbers: '+esc(summarize(g.rows,1,4))+'</p><small>'+esc(summarize(g.rows,3,2))+' · ATA '+esc(summarize(g.rows,4,3))+'<br>'+esc(summarize(g.rows,5,2))+'</small><span>View all matching parts →</span></a>').join('');
   if(groups.length){status.textContent=groups.length>8?'Showing 8 of '+groups.length+' matching component groups.':groups.length+' matching component '+(groups.length===1?'group.':'groups.');}
   else{status.textContent='No matching capabilities found.';results.innerHTML='<div class="hero-empty">Part number not listed? <a href="quote.html?part='+encodeURIComponent(heroInput.value.trim())+'">Send it to HSA →</a></div>';}
   show();
  }catch(e){if(normalize(heroInput.value)!==q)return;close();status.textContent='The capability list could not be loaded. Try again or browse all capabilities.';}
 }
 heroInput.addEventListener('input',search);
 heroInput.addEventListener('keydown',e=>{if(e.key==='Escape'){close();status.textContent=''}if(e.key==='ArrowDown'&&!results.hidden){e.preventDefault();results.querySelector('a')?.focus()}});
 results.addEventListener('keydown',e=>{const links=[...results.querySelectorAll('a')],i=links.indexOf(document.activeElement);if(e.key==='Escape'){close();heroInput.focus()}if(e.key==='ArrowDown'){e.preventDefault();links[Math.min(i+1,links.length-1)]?.focus()}if(e.key==='ArrowUp'){e.preventDefault();if(i<=0)heroInput.focus();else links[i-1].focus()}});
 if(heroInput.value)search();
}
const unitStage=document.querySelector('.hmu-stage');
if(unitStage){
 const photos=[...unitStage.querySelectorAll('.hmu-photo')],thumbs=[...document.querySelectorAll('.hmu-thumb')];
 let view=0,zoom=1,panX=0,panY=0,drag=null;
 const prev=document.querySelector('#hmu-prev'),next=document.querySelector('#hmu-next'),plus=document.querySelector('#hmu-plus'),minus=document.querySelector('#hmu-minus');
 function paint(){photos.forEach((p,i)=>p.hidden=i!==view);thumbs.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===view)));document.querySelector('#hmu-counter').textContent='VIEW '+String(view+1).padStart(2,'0')+' / 06';unitStage.style.setProperty('--unit-zoom',zoom);unitStage.style.setProperty('--pan-x',panX+'px');unitStage.style.setProperty('--pan-y',panY+'px');unitStage.classList.toggle('zoomed',zoom>1);document.querySelector('#hmu-scale').textContent=Math.round(zoom*100)+'%';document.querySelector('#hmu-hint').textContent=zoom>1?'Drag to inspect · Arrows change view':'Drag to explore · 6 photographic views';plus.disabled=zoom>=2.5;minus.disabled=zoom<=1;}
 function change(n){view=(n+photos.length)%photos.length;panX=panY=0;paint()}
 function scale(n){zoom=Math.min(2.5,Math.max(1,n));panX=panY=0;paint()}
 prev.addEventListener('click',()=>change(view-1));next.addEventListener('click',()=>change(view+1));thumbs.forEach(b=>b.addEventListener('click',()=>change(Number(b.dataset.view))));plus.addEventListener('click',()=>scale(zoom+.5));minus.addEventListener('click',()=>scale(zoom-.5));document.querySelector('#hmu-reset').addEventListener('click',()=>{view=0;scale(1)});
 unitStage.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();change(view+1)}if(e.key==='ArrowLeft'){e.preventDefault();change(view-1)}if(e.key==='+'||e.key==='='){e.preventDefault();scale(zoom+.5)}if(e.key==='-'){e.preventDefault();scale(zoom-.5)}});
 unitStage.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:panX,py:panY,view};unitStage.setPointerCapture(e.pointerId);unitStage.classList.add('dragging')});
 unitStage.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(zoom>1){const maxX=unitStage.clientWidth*(zoom-1)/2,maxY=unitStage.clientHeight*(zoom-1)/2;panX=Math.max(-maxX,Math.min(maxX,drag.px+dx));panY=Math.max(-maxY,Math.min(maxY,drag.py+dy));paint()}else if(Math.abs(dx)>Math.abs(dy)){const step=Math.trunc(dx/55);const n=((drag.view-step)%6+6)%6;if(n!==view)change(n)}});
 function stop(){drag=null;unitStage.classList.remove('dragging')}
 unitStage.addEventListener('pointerup',stop);unitStage.addEventListener('pointercancel',stop);unitStage.addEventListener('lostpointercapture',stop);
 photos.forEach(p=>p.addEventListener('error',()=>{document.querySelector('.hmu-caption').textContent='One photograph could not load. Please reload the page.'}));paint();
}
